### ISSUE TITLE
Differences with Debotnet

### ISSUE THREAD

**Issue by rnc** [mirinsoft/sharpapp#16]
Would it be possible to give a better comparison of the differences between this and debotnet? Is it possible to run these tools via the command line only? (as well as gui) - so it could be integrated into a ansible setup script.

**Comment by Belim** [comment]
I left some words here at first 
https://github.com/mirinsoft/debotnet/issues/54

Currently it would be possible with Debotnet via CLI. SharpApp does not offer CLI support yet but will come and you only have to click 2 -3 times in SharpApp anyway

**Comment by rnc** [comment]
@Belim Thanks for the information. For context, on why some form of automation would be *very* useful - I plan to have a set of Ansible scripts (using e.g. some of https://docs.ansible.com/ansible/latest/modules/list_of_windows_modules.html ) that I can run via a SSH connection and completely setup the machine, ensure chocolately packages are up to date etc. It would be great if I can call onto this program so that it could be executed as well thereby ensuring that after a Windows version update everything is still configured correctly.

I realise that an endless set of CLI flags isn't perhaps a way to go .... perhaps some way of selecting a configuring via the GUI, exporting it and being able to 'run' that config from the CLI ? (just thinking out loud :-)  )/

**Comment by Belim** [comment]
I will bear that in mind and think of something extra nice :grin:
Somehow I'm not a fan of command-line parameter :unamused:

**Comment by rnc** [comment]
Yeah I think lots of `-a -b -c` will get unwieidly far too quickly :-) hence one possible suggestion of doing a config via the GUI but being able to 'repeat' it via the command line.

**Comment by stevleibelt** [comment]
The way @rnc mentioned has being done by the privazer team.
There is only one thing we have to keep in mind and that is "how to handle outdated configuration files"?
Handle means, detect outdated version (easy by just adding a "version: 123"), migrate (maybe by importing it in the current SharpApp release) and finally marking what has being changed to ease up hand made migration.

I really like the idea since it keeps the cli interface small plus a fully imported configuration should be handled in the SharpApp the same way, either provided by cli or by gui :-).

**Comment by Belim** [comment]
I have provided some information here http://www.mirinsoft.com/blog/19-apps/27-going-forward-with-sharpapp-only
