### ISSUE TITLE
Do you plan on segmenting into several scripts like debotnet?

### ISSUE THREAD

**Issue by vdurante** [mirinsoft/sharpapp#22]
All existing ALL IN ONE scripts suffer from the same issue: they break several services/apps I use.

I love debotnet because I can control and check what I want to disable over dozens of checkboxes. I can also read the Test Run scripts and make sure it won't break or disable anything important for my daily usage.

Do you plan on segmenting sharpapp into smaller and readable scripts like debotnet used to be?

Thank you and contratulations!

**Comment by Belim** [comment]
:smiley: Yes, I've been working on it for a few days. It will be a mixture of both, as I will not discard bundled scripts/templates (for automation purposes they are are great).

Testing script files is not planned as you can check the code for vulnerabilities at any time before execution. This would not be possible without further ado, because I only provide the "real" code in the Powershell scripts

**Comment by vdurante** [comment]
@Belim Thank you very much! I am super happy now.

Regarding de Test Run: if there is a way of checking the script's code as easy as it used to be in debotnet, that would be great. It doesn't have to be a test run, just a way of reading the source code of the script.

**Comment by Belim** [comment]
Did you give it a test run? :relaxed:
https://github.com/mirinsoft/sharpapp/releases/tag/0.35.0

This time I was a little too fast

**Comment by vdurante** [comment]
I just checked the 'scripting' tab. That is nice.

**Comment by Belim** [comment]
This was implemented with build 0.35 and improved again with release 0.40 https://github.com/mirinsoft/sharpapp/releases/tag/0.40.0
This can be closed.
