### ISSUE TITLE
registry paths are not being created when missing

### ISSUE THREAD

**Issue by agentoranger** [mirinsoft/sharpapp#9]
I notice that registry paths are not being created when they are missing.  This might be intentional in some cases, but it causes an error when attempting to use new-itemproperty when the key does not exists.  Good luck, have fun.
`New-ItemProperty : Cannot find path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\software_reporter_tool.exe' because it does not exist.
At C:\Users\xAdmin\Desktop\SharpApp\scripts\appsPrivacyTemplate.ps1:10 char:1`

**Comment by Belim** [comment]
Yes, this is also an exceptional case since as this key certainly exists on the fewest machines 

I will provide an fix
`If (!(Test-Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\software_reporter_tool.exe"))
{
New-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\software_reporter_tool.exe" -Force | Out-Null
Write-Output "Google Chrome Software Reporter Tool has been successfully blocked."
}
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\software_reporter_tool.exe" -Name "Debugger" -Type String -Value %windir%\System32\taskkill.exe -Force `

If you know a better and shorter way, go ahead :smirk:
